"""add managed by admin to users

Revision ID: 118717cdfb59
Revises: d2350d410901
Create Date: 2026-07-16 11:47:07.062257

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '118717cdfb59'
down_revision: Union[str, Sequence[str], None] = 'd2350d410901'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('managed_by_admin_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_users_managed_by_admin_id'), 'users', ['managed_by_admin_id'], unique=False)
    op.create_foreign_key(None, 'users', 'users', ['managed_by_admin_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_index(op.f('ix_users_managed_by_admin_id'), table_name='users')
    op.drop_column('users', 'managed_by_admin_id')
    # ### end Alembic commands ###
