"""create script rejections table

Revision ID: 859df060932c
Revises: c465322310ea
Create Date: 2026-07-13 15:56:29.722067

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '859df060932c'
down_revision: Union[str, Sequence[str], None] = 'c465322310ea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('script_rejections',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('answer_script_id', sa.UUID(), nullable=False),
    sa.Column('rejected_by_examiner_id', sa.UUID(), nullable=False),
    sa.Column('reason', sa.String(length=100), nullable=False),
    sa.Column('examiner_remarks', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('rejected_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['answer_script_id'], ['answer_scripts.id'], ),
    sa.ForeignKeyConstraint(['rejected_by_examiner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_script_rejections_answer_script_id'), 'script_rejections', ['answer_script_id'], unique=False)
    op.create_index(op.f('ix_script_rejections_rejected_by_examiner_id'), 'script_rejections', ['rejected_by_examiner_id'], unique=False)
    op.create_index(op.f('ix_script_rejections_status'), 'script_rejections', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_script_rejections_status'), table_name='script_rejections')
    op.drop_index(op.f('ix_script_rejections_rejected_by_examiner_id'), table_name='script_rejections')
    op.drop_index(op.f('ix_script_rejections_answer_script_id'), table_name='script_rejections')
    op.drop_table('script_rejections')
    # ### end Alembic commands ###
