"""create admin review actions table

Revision ID: 96a39e17eb5c
Revises: 859df060932c
Create Date: 2026-07-13 16:13:51.807588

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '96a39e17eb5c'
down_revision: Union[str, Sequence[str], None] = '859df060932c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_review_actions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('rejection_id', sa.UUID(), nullable=False),
    sa.Column('reviewed_by_admin_id', sa.UUID(), nullable=False),
    sa.Column('decision', sa.String(length=50), nullable=False),
    sa.Column('admin_remarks', sa.Text(), nullable=True),
    sa.Column('system_message', sa.Text(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['rejection_id'], ['script_rejections.id'], ),
    sa.ForeignKeyConstraint(['reviewed_by_admin_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_admin_review_actions_decision'), 'admin_review_actions', ['decision'], unique=False)
    op.create_index(op.f('ix_admin_review_actions_rejection_id'), 'admin_review_actions', ['rejection_id'], unique=False)
    op.create_index(op.f('ix_admin_review_actions_reviewed_by_admin_id'), 'admin_review_actions', ['reviewed_by_admin_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_admin_review_actions_reviewed_by_admin_id'), table_name='admin_review_actions')
    op.drop_index(op.f('ix_admin_review_actions_rejection_id'), table_name='admin_review_actions')
    op.drop_index(op.f('ix_admin_review_actions_decision'), table_name='admin_review_actions')
    op.drop_table('admin_review_actions')
    # ### end Alembic commands ###
