"""Add institute_id to users

Revision ID: a46c4e8db82f
Revises: create_audit_logs
Create Date: 2026-07-20 11:43:27.675298

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a46c4e8db82f'
down_revision: Union[str, Sequence[str], None] = 'create_audit_logs'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade():
    # 1. Add column as nullable
    op.add_column(
        "users",
        sa.Column(
            "institute_id",
            sa.String(length=50),
            nullable=True,
        ),
    )

    # 2. Give existing users a default institute
    op.execute(
        """
        UPDATE users
        SET institute_id = 'INST-001'
        WHERE institute_id IS NULL;
        """
    )

    # 3. Make column NOT NULL
    op.alter_column(
        "users",
        "institute_id",
        nullable=False,
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'institute_id')
    # ### end Alembic commands ###
