"""create answer scripts table

Revision ID: c465322310ea
Revises: 41247c30f526
Create Date: 2026-07-13 15:48:01.772585

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c465322310ea'
down_revision: Union[str, Sequence[str], None] = '41247c30f526'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('answer_scripts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('barcode', sa.String(length=100), nullable=False),
    sa.Column('subject', sa.String(length=255), nullable=False),
    sa.Column('centre_id', sa.String(length=100), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_answer_scripts_barcode'), 'answer_scripts', ['barcode'], unique=True)
    op.create_index(op.f('ix_answer_scripts_centre_id'), 'answer_scripts', ['centre_id'], unique=False)
    op.create_index(op.f('ix_answer_scripts_status'), 'answer_scripts', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_answer_scripts_status'), table_name='answer_scripts')
    op.drop_index(op.f('ix_answer_scripts_centre_id'), table_name='answer_scripts')
    op.drop_index(op.f('ix_answer_scripts_barcode'), table_name='answer_scripts')
    op.drop_table('answer_scripts')
    # ### end Alembic commands ###
