"""add assigned examiner to answer scripts

Revision ID: d2350d410901
Revises: 96a39e17eb5c
Create Date: 2026-07-15 12:56:36.080649

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd2350d410901'
down_revision: Union[str, Sequence[str], None] = '96a39e17eb5c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('answer_scripts', sa.Column('assigned_examiner_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_answer_scripts_assigned_examiner_id'), 'answer_scripts', ['assigned_examiner_id'], unique=False)
    op.create_foreign_key(None, 'answer_scripts', 'users', ['assigned_examiner_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'answer_scripts', type_='foreignkey')
    op.drop_index(op.f('ix_answer_scripts_assigned_examiner_id'), table_name='answer_scripts')
    op.drop_column('answer_scripts', 'assigned_examiner_id')
    # ### end Alembic commands ###
